spring.application.name=enterprise-warehouse-management-system
#server Details
server.port=1111

#DB Details
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ ewms_db
spring.datasource.username=root
spring.datasource.password=root

#JPA Details
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


